### ISSUE TITLE
Eamples

### ISSUE THREAD

**Issue by pzolla** [centro/transis#42]
Would it be possible for someone to confirm if the 'examples' are loading correctly?  I am getting:

_error transis@0.9.0 prepublish: `make clean transis`_ 

Certainly can be something I am doing; not exactly an expert on npm and node although I am using it successfully elsewhere.

I simply downloaded the code, went into the root of the local folder, did 'npm install'.  npm did install a node_modules folder and a bunch of packages.  Failing at the end with:

_'make' is not recognized as an internal or external command,
operable program or batch file._

Thanks

**Comment by burrows** [comment]
@pzolla Sorry for the delay on this. You'll need to have `make` installed in order to build transis and run the examples. I'm guessing you don't have it available because you are on windows. I'm not sure what is currently the best approach to running unix utilities on windows, but one thing you could try is installing [cygwin](https://www.cygwin.com/).
